/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ConvertirRouteImport } from './routes/convertir'
import { Route as OrigineRouteImport } from './routes/origine'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertirRoute = ConvertirRouteImport.update({
  id: '/convertir',
  path: '/convertir',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigineRoute = OrigineRouteImport.update({
  id: '/origine',
  path: '/origine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/codex': typeof CodexRoute
  '/convertir': typeof ConvertirRoute
  '/origine': typeof OrigineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/codex': typeof CodexRoute
  '/convertir': typeof ConvertirRoute
  '/origine': typeof OrigineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/codex': typeof CodexRoute
  '/convertir': typeof ConvertirRoute
  '/origine': typeof OrigineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendrier' | '/codex' | '/convertir' | '/origine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendrier' | '/codex' | '/convertir' | '/origine'
  id: '__root__' | '/' | '/calendrier' | '/codex' | '/convertir' | '/origine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierRoute: typeof CalendrierRoute
  CodexRoute: typeof CodexRoute
  ConvertirRoute: typeof ConvertirRoute
  OrigineRoute: typeof OrigineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convertir': {
      id: '/convertir'
      path: '/convertir'
      fullPath: '/convertir'
      preLoaderRoute: typeof ConvertirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origine': {
      id: '/origine'
      path: '/origine'
      fullPath: '/origine'
      preLoaderRoute: typeof OrigineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierRoute: CalendrierRoute,
  CodexRoute: CodexRoute,
  ConvertirRoute: ConvertirRoute,
  OrigineRoute: OrigineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
